package com.soch.uam.domain;
// default package
// Generated Mar 23, 2017 1:46:08 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContractCompanyTb generated by hbm2java
 */
@Entity
@Table(name = "CONTRACT_COMPANY_TB")
public class ContractCompanyEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3764888927405658048L;
	private int contractCompanyId;
	private String companyName;
	private Date startDate;
	private Date endDate;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String state;
	private String zipcode;
	private Set<TempUserEntity> tempUserEntities = new HashSet<TempUserEntity>(0);
	private Set<UserWorkEntity> userWorkEntities = new HashSet<UserWorkEntity>(0);

	public ContractCompanyEntity() {
	}

	public ContractCompanyEntity(int contractCompanyId) {
		this.contractCompanyId = contractCompanyId;
	}

	@Id

	@Column(name = "CONTRACT_COMPANY_ID", unique = true, nullable = false)
	public int getContractCompanyId() {
		return this.contractCompanyId;
	}

	public void setContractCompanyId(int contractCompanyId) {
		this.contractCompanyId = contractCompanyId;
	}

	@Column(name = "COMPANY_NAME", length = 100)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DATE", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DATE", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "ADDRESS_LINE1", length = 100)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "ADDRESS_LINE2", length = 100)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "CITY", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIPCODE", length = 45)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contractCompanyEntity")
	public Set<TempUserEntity> getTempUserEntities() {
		return tempUserEntities;
	}

	public void setTempUserEntities(Set<TempUserEntity> tempUserEntities) {
		this.tempUserEntities = tempUserEntities;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contractCompanyEntity")
	public Set<UserWorkEntity> getUserWorkEntities() {
		return userWorkEntities;
	}
	
	public void setUserWorkEntities(Set<UserWorkEntity> userWorkEntities) {
		this.userWorkEntities = userWorkEntities;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
	
	
	

}
