package com.soch.uam.domain;
// Generated Oct 21, 2016 5:59:51 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DemoUser generated by hbm2java
 */
@Entity
@Table(name = "DEMO_USER")
public class DemoUserEntity implements java.io.Serializable {

	private String userId;
	private String password;

	public DemoUserEntity() {
	}

	public DemoUserEntity(String userId) {
		this.userId = userId;
	}

	public DemoUserEntity(String userId, String password) {
		this.userId = userId;
		this.password = password;
	}

	@Id

	@Column(name = "userId", unique = true, nullable = false, length = 100)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "password", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
