// default package
// Generated Feb 9, 2017 12:28:59 PM by Hibernate Tools 4.3.5.Final
package com.soch.uam.domain;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeptTb generated by hbm2java
 */
@Entity
@Table(name = "dept_tb", catalog = "sochdb")
public class DeptEntity implements java.io.Serializable {

	private int deptId;
	private String deptName;
	private String description;
	private Set<SystemEntity> systemEntitys = new HashSet<SystemEntity>(0);

	public DeptEntity() {
	}

	public DeptEntity(int deptId) {
		this.deptId = deptId;
	}

	public DeptEntity(int deptId, String deptName, String description, Set<SystemEntity> systemEntitys) {
		this.deptId = deptId;
		this.deptName = deptName;
		this.description = description;
		this.systemEntitys = systemEntitys;
	}

	@Id

	@Column(name = "dept_id", unique = true, nullable = false)
	public int getDeptId() {
		return this.deptId;
	}

	public void setDeptId(int deptId) {
		this.deptId = deptId;
	}

	@Column(name = "dept_name", length = 100)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deptEntity")
	public Set<SystemEntity> getSystemEntitys() {
		return this.systemEntitys;
	}

	public void setSystemEntitys(Set<SystemEntity> systemEntitys) {
		this.systemEntitys = systemEntitys;
	}

}
