package com.soch.uam.domain;
// default package
// Generated Apr 7, 2017 2:53:38 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExternalSourceRoleTb generated by hbm2java
 */
@Entity
@Table(name = "EXTERNAL_SOURCE_ROLE_TB")
public class ExternalSourceRoleEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7344895547770271828L;
	private String externalSourceRoleId;
	private String roleName;
	private String description;
	private Set<RolesEntity> rolesEntities = new HashSet<RolesEntity>(0);
	
	

	@Id

	@Column(name = "EXTERNAL_SOURCE_ROLE_ID", unique = true, nullable = false, length = 100)
	public String getExternalSourceRoleId() {
		return externalSourceRoleId;
	}

	public void setExternalSourceRoleId(String externalSourceRoleId) {
		this.externalSourceRoleId = externalSourceRoleId;
	}

	@Column(name = "ROLE_NAME", length = 100)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "externalSourceRoleEntity",cascade=CascadeType.ALL)
	public Set<RolesEntity> getRolesEntities() {
		return rolesEntities;
	}

	public void setRolesEntities(Set<RolesEntity> rolesEntities) {
		this.rolesEntities = rolesEntities;
	}
	
	
	
}
