package com.soch.uam.domain;
// Generated Aug 26, 2016 9:08:30 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Logintb generated by hbm2java
 */
@Entity
@Table(name = "LOGINTB")
public class LoginEntity implements java.io.Serializable {

	private Integer loginId;
	private UserEntity userEntity;
	private Date loginTs;
	private Date logOutTs;
	private boolean loginStatus;

	public LoginEntity() {
	}

	public LoginEntity(UserEntity userEntity, Date loginTs, Date logOutTs, boolean loginStatus) {
		this.userEntity = userEntity;
		this.loginTs = loginTs;
		this.logOutTs = logOutTs;
		this.loginStatus = loginStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "loginId", unique = true, nullable = false)
	public Integer getLoginId() {
		return this.loginId;
	}

	public void setLoginId(Integer loginId) {
		this.loginId = loginId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID")
	public UserEntity getUserEntity() {
		return this.userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@Column(name = "loginTs", length = 45)
	public Date getLoginTs() {
		return this.loginTs;
	}

	public void setLoginTs(Date loginTs) {
		this.loginTs = loginTs;
	}

	@Column(name = "logOutTs", length = 45)
	public Date getLogOutTs() {
		return this.logOutTs;
	}

	public void setLogOutTs(Date logOutTs) {
		this.logOutTs = logOutTs;
	}

	@Column(name = "loginStatus", length = 45)
	public boolean getLoginStatus() {
		return this.loginStatus;
	}

	public void setLoginStatus(boolean loginStatus) {
		this.loginStatus = loginStatus;
	}

}
