package com.soch.uam.domain;
// default package
// Generated Mar 9, 2017 3:08:36 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OnboardApprovalAuditTb generated by hbm2java
 */
@Entity
@Table(name = "ONBOARD_APPROVAL_AUDIT_TB")
public class OnboardApprovalAuditEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5648290821250569857L;
	private int onboardApprovalAuditId;
	private String tempUserTbEmployeeId;
	private String userTbId;
	private String message;
	 private Date aprovedOn;

	public OnboardApprovalAuditEntity() {
	}

	public OnboardApprovalAuditEntity(int onboardApprovalAuditId) {
		this.onboardApprovalAuditId = onboardApprovalAuditId;
	}
	
	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator="userSeqGen")
	@TableGenerator(
		        name="userSeqGen", 
		        table="SEQ_TB", 
		        pkColumnName="seq_name", 
		        valueColumnName="seq_val", 
		        pkColumnValue="ONBOARD_APPROVAL_AUDIT_ID", 
		        allocationSize=1)
	@Column(name = "ONBOARD_APPROVAL_AUDIT_ID", unique = true, nullable = false)
	public int getOnboardApprovalAuditId() {
		return this.onboardApprovalAuditId;
	}

	public void setOnboardApprovalAuditId(int onboardApprovalAuditId) {
		this.onboardApprovalAuditId = onboardApprovalAuditId;
	}

	@Column(name = "temp_user_tb_employee_id", length = 45)
	public String getTempUserTbEmployeeId() {
		return this.tempUserTbEmployeeId;
	}

	public void setTempUserTbEmployeeId(String tempUserTbEmployeeId) {
		this.tempUserTbEmployeeId = tempUserTbEmployeeId;
	}

	@Column(name = "user_tb_id", length = 45)
	public String getUserTbId() {
		return this.userTbId;
	}

	public void setUserTbId(String userTbId) {
		this.userTbId = userTbId;
	}

	@Column(name = "MESSAGE", length = 500)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="APROVED_ON", length=19)
	public Date getAprovedOn() {
	   return this.aprovedOn;
	}
	    
	public void setAprovedOn(Date aprovedOn) {
	    this.aprovedOn = aprovedOn;
	}

}
