package com.soch.uam.domain;
// default package
// Generated Feb 13, 2017 3:34:20 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OnboardingApprovalEntityId generated by hbm2java
 */
@Embeddable
public class OnboardingApprovalEntityId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8003444680401816376L;
	private int userEntityId;
	private int rolesEntityRoleId;

	public OnboardingApprovalEntityId() {
	}

	public OnboardingApprovalEntityId(int userEntityId, int rolesEntityRoleId) {
		this.userEntityId = userEntityId;
		this.rolesEntityRoleId = rolesEntityRoleId;
	}

	@Column(name = "USER_TB_id", nullable = false)
	public int getUserEntityId() {
		return this.userEntityId;
	}

	public void setUserEntityId(int userEntityId) {
		this.userEntityId = userEntityId;
	}

	@Column(name = "ROLES_TB_role_id", nullable = false)
	public int getRolesEntityRoleId() {
		return this.rolesEntityRoleId;
	}

	public void setRolesEntityRoleId(int rolesEntityRoleId) {
		this.rolesEntityRoleId = rolesEntityRoleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OnboardingApprovalEntityId))
			return false;
		OnboardingApprovalEntityId castOther = (OnboardingApprovalEntityId) other;

		return (this.getUserEntityId() == castOther.getUserEntityId())
				&& (this.getRolesEntityRoleId() == castOther.getRolesEntityRoleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserEntityId();
		result = 37 * result + this.getRolesEntityRoleId();
		return result;
	}

}
