package com.soch.uam.domain;
// default package
// Generated Feb 13, 2017 3:34:20 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OnboardingApprovalTb generated by hbm2java
 */
@Entity
@Table(name = "onboarding_approval_tb", catalog = "sochdb")
public class OnboardingApprovalEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1429658889020579777L;
	private OnboardingApprovalEntityId id;
	private RolesEntity rolesEntity;
	private UserEntity userEntity;
	private Integer level;

	public OnboardingApprovalEntity() {
	}

	public OnboardingApprovalEntity(OnboardingApprovalEntityId id, RolesEntity rolesEntity, UserEntity userEntity) {
		this.id = id;
		this.rolesEntity = rolesEntity;
		this.userEntity = userEntity;
	}

	public OnboardingApprovalEntity(OnboardingApprovalEntityId id, RolesEntity rolesEntity, UserEntity userEntity, Integer level) {
		this.id = id;
		this.rolesEntity = rolesEntity;
		this.userEntity = userEntity;
		this.level = level;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userTbId", column = @Column(name = "USER_TB_id", nullable = false)),
			@AttributeOverride(name = "rolesEntityRoleId", column = @Column(name = "ROLES_TB_role_id", nullable = false)) })
	public OnboardingApprovalEntityId getId() {
		return this.id;
	}

	public void setId(OnboardingApprovalEntityId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLES_TB_role_id", nullable = false, insertable = false, updatable = false)
	public RolesEntity getRolesEntity() {
		return this.rolesEntity;
	}

	public void setRolesEntity(RolesEntity rolesEntity) {
		this.rolesEntity = rolesEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_TB_id", nullable = false, insertable = false, updatable = false)
	public UserEntity getUserEntity() {
		return this.userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

}
