package com.soch.uam.domain;
// default package
// Generated Feb 13, 2017 3:34:20 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * OnboardingApprovalTb generated by hbm2java
 */
@Entity
@Table(name = "onboarding_approval_tb")
public class OnboardingApprovalEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1429658889020579777L;
	private Integer onboardApprovalId;
	private RolesEntity rolesEntity;
	private UserEntity userEntity;
	private Integer level;
	private boolean activeStatus;
	private Integer sla;
	private Integer approvalType;

	public OnboardingApprovalEntity() {
	}

	@Id

	@Column(name = "ONBOARD_APPROVAL_ID", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.TABLE, generator="userSeqGen")
	 @TableGenerator(
		        name="userSeqGen", 
		        table="SEQ_TB", 
		        pkColumnName="seq_name", 
		        valueColumnName="seq_val", 
		        pkColumnValue="ONBOARD_APPROVAL_ID", 
		        allocationSize=1)
	public Integer getOnboardApprovalId() {
		return this.onboardApprovalId;
	}

	public void setOnboardApprovalId(Integer onboardApprovalId) {
		this.onboardApprovalId = onboardApprovalId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLES_TB_role_id")
	public RolesEntity getRolesEntity() {
		return this.rolesEntity;
	}

	public void setRolesEntity(RolesEntity rolesEntity) {
		this.rolesEntity = rolesEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_TB_id")
	public UserEntity getUserEntity() {
		return this.userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}
	
	@Column(name = "ACTIVE_STATUS")
	public boolean isActiveStatus() {
		return activeStatus;
	}

	public void setActiveStatus(boolean activeStatus) {
		this.activeStatus = activeStatus;
	}
	
	@Column(name = "SLA")
	public Integer getSla() {
		return sla;
	}

	public void setSla(Integer sla) {
		this.sla = sla;
	}
	
	@Column(name = "APPROVAL_TYPE")
	public Integer getApprovalType() {
		return approvalType;
	}

	public void setApprovalType(Integer approvalType) {
		this.approvalType = approvalType;
	}
	
	
	
	

}
