package com.soch.uam.domain;
// default package
// Generated Dec 26, 2016 4:27:28 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PolicyGrpTb generated by hbm2java
 */
@Entity
@Table(name = "POLICY_GRP_TB", catalog = "sochdb")
public class PolicyGrpEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6353665976745682781L;
	private int policyGrpId;
	private String policyGrpName;
	private Set<PolicySrcEntity> policySrcTbs = new HashSet<PolicySrcEntity>(0);

	public PolicyGrpEntity() {
	}

	public PolicyGrpEntity(int policyGrpId) {
		this.policyGrpId = policyGrpId;
	}

	public PolicyGrpEntity(int policyGrpId, String policyGrpName, Set<PolicySrcEntity> policySrcTbs) {
		this.policyGrpId = policyGrpId;
		this.policyGrpName = policyGrpName;
		this.policySrcTbs = policySrcTbs;
	}

	@Id
	@Column(name = "POLICY_GRP_ID", unique = true, nullable = false)
	public int getPolicyGrpId() {
		return this.policyGrpId;
	}

	public void setPolicyGrpId(int policyGrpId) {
		this.policyGrpId = policyGrpId;
	}

	@Column(name = "POLICY_GRP_NAME", length = 100)
	public String getPolicyGrpName() {
		return this.policyGrpName;
	}

	public void setPolicyGrpName(String policyGrpName) {
		this.policyGrpName = policyGrpName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policyGrpEntity",cascade = CascadeType.ALL)
	public Set<PolicySrcEntity> getPolicySrcTbs() {
		return this.policySrcTbs;
	}

	public void setPolicySrcTbs(Set<PolicySrcEntity> policySrcTbs) {
		this.policySrcTbs = policySrcTbs;
	}

}
