package com.soch.uam.domain;
// default package
// Generated Dec 26, 2016 4:27:28 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PolicySrcTb generated by hbm2java
 */
@Entity
@Table(name = "POLICY_SRC_TB", catalog = "sochdb")
public class PolicySrcEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5943600606740905055L;
	private int policyId;
	private PolicyGrpEntity policyGrpEntity;
	private String policyName;
	private String policyDesc;
	private String vitaVal;
	private String cmsVal;

	public PolicySrcEntity() {
	}
	
	public PolicySrcEntity(int policyId) {
		this.policyId = policyId;
	}

	public PolicySrcEntity(int policyId, PolicyGrpEntity policyGrpTb, String policyName, String policyDesc, String vitaVal,
			String cmsVal) {
		this.policyId = policyId;
		this.policyGrpEntity = policyGrpTb;
		this.policyName = policyName;
		this.policyDesc = policyDesc;
		this.vitaVal = vitaVal;
		this.cmsVal = cmsVal;
	}

	@Id
	@Column(name = "POLICY_ID", unique = true, nullable = false)
	public int getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(int policyId) {
		this.policyId = policyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POLICY_GRP_ID", insertable = true, updatable = true, nullable = false)
	public PolicyGrpEntity getPolicyGrpEntity() {
		return this.policyGrpEntity;
	}

	public void setPolicyGrpEntity(PolicyGrpEntity policyGrpEntity) {
		this.policyGrpEntity = policyGrpEntity;
	}

	@Column(name = "POLICY_NAME", length = 100)
	public String getPolicyName() {
		return this.policyName;
	}

	public void setPolicyName(String policyName) {
		this.policyName = policyName;
	}

	@Column(name = "POLICY_DESC", length = 500)
	public String getPolicyDesc() {
		return this.policyDesc;
	}

	public void setPolicyDesc(String policyDesc) {
		this.policyDesc = policyDesc;
	}

	@Column(name = "VITA_VAL", length = 45)
	public String getVitaVal() {
		return this.vitaVal;
	}

	public void setVitaVal(String vitaVal) {
		this.vitaVal = vitaVal;
	}

	@Column(name = "CMS_VAL", length = 45)
	public String getCmsVal() {
		return this.cmsVal;
	}

	public void setCmsVal(String cmsVal) {
		this.cmsVal = cmsVal;
	}

}
