package com.soch.uam.domain;
// Generated Sep 30, 2016 10:01:12 PM by Hibernate Tools 4.3.4.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PolicyConfigTb generated by hbm2java
 */
@Entity
@Table(name = "POLICY_CONFIG_TB")
public class PolicyConfigEntity implements java.io.Serializable {

	private String policyName;
	private String value;
	private String createdBy;
	private Date createdTs;
	private String modifiedBy;
	private Date modifiedTs;
	private String notes;
	
	

	public PolicyConfigEntity() {
	}

	public PolicyConfigEntity(String policyName) {
		this.policyName = policyName;
	}

	public PolicyConfigEntity(String policyName, String value, String policyConfigTbcol, String createdBy, Date createdTs,
			String modifiedBy, Date modifiedTs) {
		this.policyName = policyName;
		this.value = value;
		this.createdBy = createdBy;
		this.createdTs = createdTs;
		this.modifiedBy = modifiedBy;
		this.modifiedTs = modifiedTs;
	}

	@Id
	@Column(name = "POLICY_NAME", unique = true, nullable = false, length = 100)
	public String getPolicyName() {
		return this.policyName;
	}

	public void setPolicyName(String policyName) {
		this.policyName = policyName;
	}

	@Column(name = "VALUE", length = 100)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	

	@Column(name = "CREATED_BY", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "MODIFIED_BY", length = 45)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_TS", length = 19)
	public Date getModifiedTs() {
		return this.modifiedTs;
	}

	public void setModifiedTs(Date modifiedTs) {
		this.modifiedTs = modifiedTs;
	}
	
	@Column(name = "NOTES", length = 500)
	public String getNotes() {
		return notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}
	
	
}
