package com.soch.uam.domain;
// default package
// Generated Apr 17, 2017 12:06:10 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PwdHistoryTb generated by hbm2java
 */
@Entity
@Table(name = "PWD_HISTORY_TB")
public class PwdHistoryEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6025469744889198636L;
	private int pwdHistoryId;
	private UserEntity userEntity;
	private String password;
	private Date createdTs;
	private String createdBy;

	
	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator="SeqGen")
	@TableGenerator(
		        name="SeqGen", 
		        table="SEQ_TB", 
		        pkColumnName="seq_name", 
		        valueColumnName="seq_val", 
		        pkColumnValue="USER_TB.ID", 
		        allocationSize=1)
	@Column(name = "PWD_HISTORY_ID", unique = true, nullable = false)
	public int getPwdHistoryId() {
		return this.pwdHistoryId;
	}

	public void setPwdHistoryId(int pwdHistoryId) {
		this.pwdHistoryId = pwdHistoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID")
	public UserEntity getUserEntity() {
		return userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@Column(name = "PASSWORD", length = 45)
	public String getPassword() {
		return this.password;
	}



	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "CREATED_BY", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
