package com.soch.uam.domain;
// Generated Oct 10, 2016 9:54:50 PM by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RolesTb generated by hbm2java
 */
@Entity
@Table(name = "ROLES_TB")
public class RolesEntity implements java.io.Serializable {

	private int roleId;
	private String roleName;
	private String roleDescription;
	private Set<UserRoleEntity> userRoleEntities = new HashSet<UserRoleEntity>(0);

	public RolesEntity() {
	}

	public RolesEntity(int roleId) {
		this.roleId = roleId;
	}

	public RolesEntity(int roleId, String roleName, String roleDescription, Set<UserRoleEntity> userRoleEntities) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleDescription = roleDescription;
		this.userRoleEntities = userRoleEntities;
	}

	@Id

	@Column(name = "role_id", unique = true, nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role name", length = 45)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_description", length = 200)
	public String getRoleDescription() {
		return this.roleDescription;
	}

	public void setRoleDescription(String roleDescription) {
		this.roleDescription = roleDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rolesEntity")
	public Set<UserRoleEntity> getUserRoleEntities() {
		return this.userRoleEntities;
	}

	public void setUserRoleEntities(Set<UserRoleEntity> userRoleEntities) {
		this.userRoleEntities = userRoleEntities;
	}

}
