package com.soch.uam.domain;
// Generated Aug 26, 2016 9:08:30 PM by Hibernate Tools 4.3.4.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Secauthtokentb generated by hbm2java
 */
@Entity
@Table(name = "SECAUTHTOKENTB")
public class SecauthtokenEntity implements java.io.Serializable {

	private String authToken;
	private UserEntity userEntity;
	private Date createdTs;
	private Date lastAccessTs;
	private boolean status;
	private String createdBy;

	public SecauthtokenEntity() {
	}

	public SecauthtokenEntity(String authToken, UserEntity userEntity) {
		this.authToken = authToken;
		this.userEntity = userEntity;
	}

	public SecauthtokenEntity(String authToken, UserEntity userEntity, Date createdTs, Date lastAccessTs, boolean status,
			String createdBy) {
		this.authToken = authToken;
		this.userEntity = userEntity;
		this.createdTs = createdTs;
		this.lastAccessTs = lastAccessTs;
		this.status = status;
		this.createdBy = createdBy;
	}

	@Id
	@Column(name = "Auth_token", unique = true, nullable = false, length = 100)
	public String getAuthToken() {
		return this.authToken;
	}

	public void setAuthToken(String authToken) {
		this.authToken = authToken;
	}

	

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id", nullable = false)
	public UserEntity getUserEntity() {
		return userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}
	
	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdTS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastAccessTS", length = 19)
	public Date getLastAccessTs() {
		return this.lastAccessTs;
	}

	public void setLastAccessTs(Date lastAccessTs) {
		this.lastAccessTs = lastAccessTs;
	}

	@Column(name = "status", length = 1)
	public boolean getStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "createdBy", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
