// default package
// Generated Feb 9, 2017 12:28:59 PM by Hibernate Tools 4.3.5.Final
package com.soch.uam.domain;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserRoleTb generated by hbm2java
 */
@Entity
@Table(name="USER_ROLE_TB"
    ,catalog="sochdb"
)
public class UserRoleEntity  implements java.io.Serializable {


     private int userRoleId;
     private RolesEntity rolesEntity;
     private UserEntity userEntity;
     private String createdBy;
     private Date createdTs;
     private String modifiedBy;
     private Date modifiedTs;

    public UserRoleEntity() {
    }

	
    public UserRoleEntity(int userRoleId) {
        this.userRoleId = userRoleId;
    }
    public UserRoleEntity(int userRoleId, RolesEntity rolesEntity, UserEntity userEntity, String createdBy, Date createdTs, String modifiedBy, Date modifiedTs) {
       this.userRoleId = userRoleId;
       this.rolesEntity = rolesEntity;
       this.userEntity = userEntity;
       this.createdBy = createdBy;
       this.createdTs = createdTs;
       this.modifiedBy = modifiedBy;
       this.modifiedTs = modifiedTs;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.TABLE, generator="userSeqGen")
	 @TableGenerator(
		        name="userSeqGen", 
		        table="SEQ_TB", 
		        pkColumnName="seq_name", 
		        valueColumnName="seq_val", 
		        pkColumnValue="user_role_id", 
		        allocationSize=1)
    
    @Column(name="user_role_id", unique=true, nullable=false)
    public int getUserRoleId() {
        return this.userRoleId;
    }
    
    public void setUserRoleId(int userRoleId) {
        this.userRoleId = userRoleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_id")
    public RolesEntity getRolesEntity() {
        return this.rolesEntity;
    }
    
    public void setRolesEntity(RolesEntity rolesEntity) {
        this.rolesEntity = rolesEntity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id")
    public UserEntity getUserEntity() {
        return this.userEntity;
    }
    
    public void setUserEntity(UserEntity userEntity) {
        this.userEntity = userEntity;
    }

    
    @Column(name="created_by", length=45)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_ts", length=19)
    public Date getCreatedTs() {
        return this.createdTs;
    }
    
    public void setCreatedTs(Date createdTs) {
        this.createdTs = createdTs;
    }

    
    @Column(name="modified_by", length=45)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_ts", length=19)
    public Date getModifiedTs() {
        return this.modifiedTs;
    }
    
    public void setModifiedTs(Date modifiedTs) {
        this.modifiedTs = modifiedTs;
    }




}


