package com.soch.uam.domain;
// default package
// Generated Apr 3, 2017 12:14:10 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * UserNotesTb generated by hbm2java
 */
@Entity
@Table(name = "USER_NOTES_TB")
public class UserNotesEntity implements java.io.Serializable {

	private int userNotesId;
	private UserEntity userEntity;
	private String notes;
	private Date createdTs;
	private String createdBy;

	public UserNotesEntity() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator="SeqGen")
	@TableGenerator(
		        name="SeqGen", 
		        table="SEQ_TB", 
		        pkColumnName="seq_name", 
		        valueColumnName="seq_val", 
		        pkColumnValue="user_notes_id", 
		        allocationSize=1)
	@Column(name = "user_notes_id", unique = true, nullable = false)
	public int getUserNotesId() {
		return this.userNotesId;
	}

	public void setUserNotesId(int userNotesId) {
		this.userNotesId = userNotesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id")
	public UserEntity getUserEntity() {
		return this.userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@Column(name = "notes", length = 500)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "created_ts", length = 45)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "created_by", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
