package com.soch.uam.domain;
// default package
// Generated Apr 19, 2017 10:00:21 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserActivityTb generated by hbm2java
 */
@Entity
@Table(name = "USER_ACTIVITY_TB")
public class UserActivityEntity implements java.io.Serializable {

	private int id;
	private UserEntity userEntity;
	private String activityType;
	private boolean activityStatus;
	private Date activityCreateTs;
	private String activityCreatedBy;


	@Id
	@Column(name = "USER_ACTIVITY_ID")
	@GeneratedValue(strategy = GenerationType.TABLE, generator="seqGen")
	@TableGenerator(
		        name="seqGen", 
		        table="SEQ_TB", 
		        pkColumnName="seq_name", 
		        valueColumnName="seq_val", 
		        pkColumnValue="USER_ACTIVITY_ID", 
		        allocationSize=1)
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTIVITY_CREATED_FOR")
	public UserEntity getUserEntity() {
		return userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@Column(name = "ACTIVITY_TYPE", length = 500)
	public String getActivityType() {
		return this.activityType;
	}

	public void setActivityType(String activityType) {
		this.activityType = activityType;
	}

	@Column(name = "ACTIVITY_STATUS", length = 1)
	public boolean getActivityStatus() {
		return this.activityStatus;
	}

	public void setActivityStatus(boolean activityStatus) {
		this.activityStatus = activityStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACTIVITY_CREATE_TS", length = 19)
	public Date getActivityCreateTs() {
		return this.activityCreateTs;
	}

	public void setActivityCreateTs(Date activityCreateTs) {
		this.activityCreateTs = activityCreateTs;
	}

	@Column(name = "ACTIVITY_CREATED_BY")
	public String getActivityCreatedBy() {
		return this.activityCreatedBy;
	}

	public void setActivityCreatedBy(String activityCreatedBy) {
		this.activityCreatedBy = activityCreatedBy;
	}

}
