package com.soch.de.domain;
// Generated Sep 30, 2016 10:01:12 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * AttemptFailureTb generated by hbm2java
 */
@Entity
@Table(name = "ATTEMPT_FAILURE_TB")
public class AttemptFailureEntity implements java.io.Serializable {

	private int id;
	private UserEntity userEntity;
	private Integer retUid;
	private Integer retPwd;
	private Integer login;

	public AttemptFailureEntity() {
	}

	public AttemptFailureEntity(UserEntity userTb) {
		this.userEntity = userTb;
	}

	public AttemptFailureEntity(UserEntity userTb, Integer retUid, Integer retPwd, Integer login) {
		this.userEntity = userTb;
		this.retUid = retUid;
		this.retPwd = retPwd;
		this.login = login;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "userTb"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public UserEntity getUserEntity() {
		return userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@Column(name = "RET_UID")
	public Integer getRetUid() {
		return this.retUid;
	}



	public void setRetUid(Integer retUid) {
		this.retUid = retUid;
	}

	@Column(name = "RET_PWD")
	public Integer getRetPwd() {
		return this.retPwd;
	}

	public void setRetPwd(Integer retPwd) {
		this.retPwd = retPwd;
	}

	@Column(name = "LOGIN")
	public Integer getLogin() {
		return this.login;
	}

	public void setLogin(Integer login) {
		this.login = login;
	}

}
