package com.soch.de.domain;
// Generated Sep 3, 2016 1:45:48 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ConfigTb generated by hbm2java
 */
@Entity
@Table(name = "CONFIG_TB")
public class ConfigEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2168685399785012714L;
	
	
	private String configName;
	private String configValue;

	public ConfigEntity() {
	}

	public ConfigEntity(String configName) {
		this.configName = configName;
	}

	public ConfigEntity(String configName, String configValue) {
		this.configName = configName;
		this.configValue = configValue;
	}

	@Id

	@Column(name = "config_name", unique = true, nullable = false, length = 100)
	public String getConfigName() {
		return this.configName;
	}

	public void setConfigName(String configName) {
		this.configName = configName;
	}

	@Column(name = "config_value", length = 45)
	public String getConfigValue() {
		return this.configValue;
	}

	public void setConfigValue(String configValue) {
		this.configValue = configValue;
	}

}
