package com.soch.de.domain;
// default package
// Generated Feb 13, 2017 3:34:20 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * OnboardApprovalPendingTb generated by hbm2java
 */
@Entity
@Table(name = "onboard_approval_pending_tb")
public class OnboardApprovalPendingEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6091095399169753311L;
	
	private int onboardPendingId;
	private TempUserEntity tempUserEntity;
	private UserEntity userEntity;
	private UserEntity requestUserEntity;
	private Date requestDate;
	private Date approveDate;
	private String requestType;
	private boolean pendingApproval;
	private Integer level;
	
	private Integer roleID;
	
	
	@Column(name = "pending_approval", length = 1)
	public boolean isPendingApproval() {
		return pendingApproval;
	}

	public void setPendingApproval(boolean pendingApproval) {
		this.pendingApproval = pendingApproval;
	}
	
	public OnboardApprovalPendingEntity() {
	}

	public OnboardApprovalPendingEntity(int onboardPendingId) {
		this.onboardPendingId = onboardPendingId;
	}

	public OnboardApprovalPendingEntity(int onboardPendingId, TempUserEntity tempUserEntity, UserEntity userEntity, Date requesDate) {
		this.onboardPendingId = onboardPendingId;
		this.tempUserEntity = tempUserEntity;
		this.userEntity = userEntity;
		this.requestDate = requestDate;
	}

	@Id
	@Column(name = "onboard_pending_id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.TABLE, generator="approvalSeqGen")
	 @TableGenerator(
		        name="approvalSeqGen", 
		        table="SEQ_TB", 
		        pkColumnName="seq_name", 
		        valueColumnName="seq_val", 
		        pkColumnValue="onboard_approval_pending_tb.onboard_pending_id", 
		        allocationSize=1)
	public int getOnboardPendingId() {
		return this.onboardPendingId;
	}

	public void setOnboardPendingId(int onboardPendingId) {
		this.onboardPendingId = onboardPendingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "temp_user_tb_employee_id")
	public TempUserEntity getTempUserEntity() {
		return this.tempUserEntity;
	}

	public void setTempUserEntity(TempUserEntity tempUserEntity) {
		this.tempUserEntity = tempUserEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_tb_id")
	public UserEntity getUserEntity() {
		return this.userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@Column(name="request_type", length=45)
    public String getRequestType() {
        return this.requestType;
    }
    
    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="request_date", length=19)
    public Date getRequestDate() {
        return this.requestDate;
    }
    
    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }
    
    @Column(name="level")
	public Integer getLevel() {
		return level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}
	
	@Column(name="roleId")
	public Integer getRoleID() {
		return roleID;
	}

	public void setRoleID(Integer roleID) {
		this.roleID = roleID;
	}
	
	@Column(name="approve_date")
	public Date getApproveDate() {
		return approveDate;
	}

	public void setApproveDate(Date approveDate) {
		this.approveDate = approveDate;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "req_user_id")
	public UserEntity getRequestUserEntity() {
		return requestUserEntity;
	}

	public void setRequestUserEntity(UserEntity requestUserEntity) {
		this.requestUserEntity = requestUserEntity;
	}
    
	
    

}
