package com.soch.de.domain;
// Generated Oct 7, 2016 10:51:11 PM by Hibernate Tools 4.3.4.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OtpTb generated by hbm2java
 */
@Entity
@Table(name = "OTP_TB")
public class OTPEntity implements java.io.Serializable {

	private Integer otpId;
	private UserEntity userEntity;
	private String oneTimePwd;
	private Date createdTs;
	private boolean activeFlag;

	public OTPEntity() {
	}

	public OTPEntity(UserEntity userEntity, String oneTimePwd, Date createdTs, boolean activeFlag) {
		this.userEntity = userEntity;
		this.oneTimePwd = oneTimePwd;
		this.createdTs = createdTs;
		this.activeFlag = activeFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "otpId", unique = true, nullable = false)
	public Integer getOtpId() {
		return this.otpId;
	}

	public void setOtpId(Integer otpId) {
		this.otpId = otpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id")
	public UserEntity getUserEntity() {
		return this.userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@Column(name = "oneTimePWD", length = 100)
	public String getOneTimePwd() {
		return this.oneTimePwd;
	}

	public void setOneTimePwd(String oneTimePwd) {
		this.oneTimePwd = oneTimePwd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdTs", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}
	
	@Column(name = "activeFlag", length = 1)
	public boolean getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

}
