package com.soch.de.domain;
// default package
// Generated Apr 6, 2017 2:00:48 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PolicySrcNotesTb generated by hbm2java
 */
@Entity
@Table(name = "POLICY_SRC_NOTES_TB")
public class PolicySrcNotesEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2143756389840116218L;
	private int policySrcNotesId;
	private PolicySrcEntity policySrcEntity;
	private String notes;
	private String createdBy;
	private Date createdTs;

	public PolicySrcNotesEntity() {
	}

	public PolicySrcNotesEntity(int policySrcNotesId) {
		this.policySrcNotesId = policySrcNotesId;
	}

	
	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator="userSeqGen")
	@TableGenerator(
		        name="userSeqGen", 
		        table="SEQ_TB", 
		        pkColumnName="seq_name", 
		        valueColumnName="seq_val", 
		        pkColumnValue="POLICY_SRC_NOTES_ID", 
		        allocationSize=1)
	@Column(name = "POLICY_SRC_NOTES_ID", unique = true, nullable = false)
	public int getPolicySrcNotesId() {
		return this.policySrcNotesId;
	}

	public void setPolicySrcNotesId(int policySrcNotesId) {
		this.policySrcNotesId = policySrcNotesId;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
	@JoinColumn(name = "POLICY_ID")
	public PolicySrcEntity getPolicySrcEntity() {
		return policySrcEntity;
	}

	public void setPolicySrcEntity(PolicySrcEntity policySrcEntity) {
		this.policySrcEntity = policySrcEntity;
	}

	@Column(name = "NOTES", length = 500)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "CREATED_BY", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

}
