package com.soch.de.domain;
// default package
// Generated Apr 3, 2017 12:14:10 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoleMappingTb generated by hbm2java
 */
@Entity
@Table(name = "ROLE_MAPPING_TB")
public class RoleMappingEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5233718891294395970L;
	private int roleMappingId;
	private Integer iamRoleId;
	private RolesEntity rolesEntity;
	private Integer otherRoleId;
	private String otherRoleName;
	private String type;


	public RoleMappingEntity(int roleMappingId) {
		this.roleMappingId = roleMappingId;
	}

	

	@Id

	@Column(name = "ROLE_MAPPING_ID", unique = true, nullable = false)
	public int getRoleMappingId() {
		return this.roleMappingId;
	}

	public void setRoleMappingId(int roleMappingId) {
		this.roleMappingId = roleMappingId;
	}

	@Column(name = "IAM_ROLE_ID")
	public Integer getIamRoleId() {
		return this.iamRoleId;
	}

	public void setIamRoleId(Integer iamRoleId) {
		this.iamRoleId = iamRoleId;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_ID")
	public RolesEntity getRolesEntity() {
		return rolesEntity;
	}

	public void setRolesEntity(RolesEntity rolesEntity) {
		this.rolesEntity = rolesEntity;
	}



	@Column(name = "OTHER_ROLE_ID")
	public Integer getOtherRoleId() {
		return this.otherRoleId;
	}

	public void setOtherRoleId(Integer otherRoleId) {
		this.otherRoleId = otherRoleId;
	}

	@Column(name = "OTHER_ROLE_NAME", length = 100)
	public String getOtherRoleName() {
		return this.otherRoleName;
	}

	public void setOtherRoleName(String otherRoleName) {
		this.otherRoleName = otherRoleName;
	}

	@Column(name = "TYPE", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
