package com.soch.de.domain;
// default package
// Generated Mar 13, 2017 12:28:56 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * TempUserRoleTb generated by hbm2java
 */
@Entity
@Table(name = "temp_user_role_tb")
public class TempUserRoleEntity implements java.io.Serializable {

	private int tempUserRoleId;
	private TempUserEntity tempUserEntity;
	private RolesEntity rolesEntity;

	public TempUserRoleEntity() {
	}

	public TempUserRoleEntity(int tempUserRoleId) {
		this.tempUserRoleId = tempUserRoleId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator="userSeqGen")
	 @TableGenerator(
		        name="userSeqGen", 
		        table="SEQ_TB", 
		        pkColumnName="seq_name", 
		        valueColumnName="seq_val", 
		        pkColumnValue="temp_user_role_id", 
		        allocationSize=1)
	@Column(name = "temp_user_role_id", unique = true, nullable = false)
	public int getTempUserRoleId() {
		return this.tempUserRoleId;
	}

	public void setTempUserRoleId(int tempUserRoleId) {
		this.tempUserRoleId = tempUserRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_Id")
	public TempUserEntity getTempUserEntity() {
		return tempUserEntity;
	}

	public void setTempUserEntity(TempUserEntity tempUserEntity) {
		this.tempUserEntity = tempUserEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", insertable=true, updatable=true)
	public RolesEntity getRolesEntity() {
		return rolesEntity;
	}

	public void setRolesEntity(RolesEntity rolesEntity) {
		this.rolesEntity = rolesEntity;
	}

}
